### PR TITLE
fix: remove the lines limit on the signal activity

### LINKED ISSUE #444: Fix: friend signal display modification
### Current behaviour
When the signal sentence is long, it gets cut out
The time is not aligned as it is shown on the design

Image

### Expected behavior
Signal text should not get cut out  as show below
the time should be places at the end of the signal text

Image

### PR DESCRIPTION
**Pull request by Jonath-z**
close #444

### CODE REVIEW

File: components/cards/UserAvailability.tsx [hunk 1]
```diff
@@ -21,46 +21,43 @@ export default function UserAvailability({
...
     maxWidth: "70%",
   },
   time: {
-    opacity: 0.5,
     textTransform: "capitalize",
-  },
-  status: {
-    maxWidth: "80%",
+    // Opacity itselt cannot work here due to text nesting
+    color: "rgba(0, 0, 0,0.5)",
```
Comment (Odile078) [inline components/cards/UserAvailability.tsx:54]: in the colors configured in the theme.ts file `rgba(0, 0, 0,0.5)` corresponds to `theme.colors.black_500` , 
```suggestion
    color: theme.colors.black_500,
```

File: components/cards/UserAvailability.tsx [hunk 2]
```diff
@@ -21,46 +21,43 @@ export default function UserAvailability({
...
   },
   dot: {
-    backgroundColor: theme.colors.black,
     opacity: 0.5,
```
Comment (Odile078) [inline components/cards/UserAvailability.tsx:57]: we probably no longer need this opacity if the color used has the opacity

File: components/cards/UserAvailability.tsx [hunk 3]
```diff
@@ -21,46 +21,43 @@ export default function UserAvailability({
...
-    height: 2,
-    width: 2,
-    borderRadius: 2,
-    marginTop: 12,
+    // Opacity itselt cannot work here due to text nesting
+    color: "rgba(0, 0, 0,0.5)",
```
Comment (Odile078) [inline components/cards/UserAvailability.tsx:59]:
```suggestion
    color: theme.colors.black_500,
```

**Review by mhenriette — APPROVED** [review]

**Review by Odile078 — APPROVED** [review]
