### PR TITLE
Fix: only create new user account when username is provided

### LINKED ISSUE #187: Fix: create the user only when the username is provided (on the canister and on the apk)
Currently when the use clicks on the email but close the process of adding the username, the account is already there.
The task is to reverse the process so that we only create the account when the username is also added.

### PR DESCRIPTION
**Pull request by serapieTuyishime**
Closes #187

### CODE REVIEW

File: contexts/AuthContext.tsx [hunk 1]
```diff
@@ -53,29 +88,17 @@ export const AuthProvider: React.FC<{ children: ReactNode }> = ({
...
-          profilePictureUrl,
-        } = data
-        const user: User = {
-          id,
-          names,
-          email,
-          username,
-          profilePictureUrl: profilePictureUrl,
+        setGoogleToken(idToken)
+        // 202 means that the new user data has been accepted for processing.
```
Comment (igorntwari) [inline contexts/AuthContext.tsx:96]: can you remove this comment

**Review by igorntwari — CHANGES_REQUESTED** [review]

**Review by igorntwari — APPROVED** [review]

**Review by mhenriette — APPROVED** [review]
