### PR TITLE
Fix: the switch button to be stuck in the middle.

### LINKED ISSUE #252: switcher  in middle position
### Description

sometimes at startup the switcher is in the middle position, not on, not off. This behaviour is observed when the app is fully loaded and internet is available. 

### Environment
* Device: Google Pixel 6
* Operating system: android 13

### Expected Behaviour
 - The switcher should either be on or off few seconds after the app loads.
 
### Actual Behaviour
- Sometimes the switcher stays in the middle of the toggle and does not change position.

### Steps to Reproduce
- on an Android device, open the app for the first time using a slow internet.
- Try as many times as possible because this behaviour is not visible all the time
- observe the behaviour on the tap to edit.

### Screenshots or Attachments
Image

### PR DESCRIPTION
**Pull request by serapieTuyishime**
Closes #252

### CODE REVIEW

File: contexts/AuthContext.tsx [hunk 1]
```diff
@@ -149,6 +149,20 @@ export const AuthProvider: React.FC<{ children: ReactNode }> = ({
...
   }, [queryClient])
 
+  const prefetchSignal = useCallback(async () => {
+    await queryClient.prefetchQuery({
+      queryKey: ["fetch-my-signal"],
+      queryFn: async () => {
+        const { data } = await api.get("/my-signal")
+        const signal = {
+          ...data,
+          friendIds: data.friends.map((friend: any) => friend?.friendId),
```
Comment (igorntwari) [inline contexts/AuthContext.tsx:159]: we have friend type

File: contexts/AuthContext.tsx [hunk 2]
```diff
@@ -149,6 +149,20 @@ export const AuthProvider: React.FC<{ children: ReactNode }> = ({
     })
   }, [queryClient])
 
+  const prefetchSignal = useCallback(async () => {
+    await queryClient.prefetchQuery({
+      queryKey: ["fetch-my-signal"],
+      queryFn: async () => {
+        const { data } = await api.get("/my-signal")
```
Comment (igorntwari) [inline contexts/AuthContext.tsx:156]: if this call fails there's is no error handling for this case

**Review by igorntwari — CHANGES_REQUESTED** [review]

**Review by igorntwari — APPROVED** [review]

**Review by Odile078 — APPROVED** [review]
