### PR TITLE
 fix Status line spacing

### LINKED ISSUE #349: Fix: Status line spacing
Check the line spacing of the status card.
The line spacing in "this status is not visible to anyone" is not correct and is the same spacing as the gap to the next sentence which, as a rule, shouldn't happen unless there is a super specific reason for doing so

Image

### PR DESCRIPTION
**Pull request by igorntwari**
closes #349

### CODE REVIEW

**Review by mhenriette — APPROVED** [review]

File: components/cards/UserAvailability.tsx [hunk 1]
```diff
@@ -61,4 +62,7 @@ const styles = StyleSheet.create({
     borderRadius: 2,
     marginTop: 12,
   },
+  activity: {
+    lineHeight: 20,
+  },
```
Comment (Odile078) [inline components/cards/UserAvailability.tsx:67]: we don't need this style since the text for the activity has fontsize `15`. So here it can use `CustomText` 's default size is `base`, which has `fontsize: 15 and lineheight: 24`
image

**Review by Odile078 — APPROVED** [review]
