### PR TITLE
fix: remove showing that user has no friends when they do

### LINKED ISSUE #113: Stay on the spash screen while the app is still fetching your friends, instead of showing the "<Nofriends/>" screen.

### PR DESCRIPTION
**Pull request by serapieTuyishime**
Closes #113

### CODE REVIEW

**Review by igorntwari — APPROVED** [review]

File: hooks/useFriends.ts [hunk 1]
```diff
@@ -24,6 +25,7 @@ export const useFriends = () => {
   }, [friends, availableFriends])
 
   const hasFriends = useMemo(() => {
+    if(isLoading) return true
```
Comment (Odile078) [inline hooks/useFriends.ts:28]: why are we setting hasFriends to true while still loading?

Comment (serapieTuyishime) [reply hooks/useFriends.ts:28]: There is a split second where the noFriends screen still shows,

File: hooks/useFriends.ts [hunk 2]
```diff
@@ -24,6 +25,7 @@ export const useFriends = () => {
...
     return friends.length !== 0
   }, [friends])
```
Comment (Odile078) [inline hooks/useFriends.ts:30]:
```suggestion
  }, [friends,isLoading])
```

**Review by Odile078 — APPROVED** [review]
