### PR TITLE
fix: log in for new user inconsistency

### LINKED ISSUE #197: The user is navigated to `Enter your name` screen instead of signin screen

### PR DESCRIPTION
**Pull request by mhenriette**
Closes #197

### CODE REVIEW

File: contexts/AuthContext.tsx [hunk 1]
```diff
@@ -16,11 +16,12 @@ import {
 import { Platform } from "react-native"
 import { User } from "@/types"
 import api from "@/service"
+import { NativeStackNavigationProp } from "@react-navigation/native-stack"
 
 interface AuthContextData {
   user: User | null
   isLoading: boolean
-  signInWithGoogle: () => Promise<void>
+  signInWithGoogle: (navigation:any) => Promise<void>
```
Comment (igorntwari) [inline contexts/AuthContext.tsx:24]: can you give another type which is not any

File: contexts/AuthContext.tsx [hunk 2]
```diff
@@ -81,20 +82,22 @@ export const AuthProvider: React.FC<{ children: ReactNode }> = ({
     await signIn(data)
   }
 
-  const signInWithGoogle = async () => {
+  const signInWithGoogle = async (navigation:any) => {
```
Comment (igorntwari) [inline contexts/AuthContext.tsx:85]: here also

**Review by igorntwari — CHANGES_REQUESTED** [review]

**Review by igorntwari — APPROVED** [review]

File: navigation/index.tsx [hunk 3]
```diff
@@ -12,7 +12,9 @@ import EntryScreen from "@/screens/Authentication"
 import CreateCredentials from "@/screens/Authentication/SignUp/CreateCredentials"
 import { StatusProvider } from "@/contexts/StatusContext"
 import { useFriends } from "@/hooks/useFriends"
-import CustomSplashScreen from "@/screens/CustomSplashScreen"
+// import CustomSplashScreen from "@/screens/CustomSplashScreen"
```
Comment (Odile078) [inline navigation/index.tsx]: remove the commented line

**Review by Odile078 — APPROVED** [review]
