### PR TITLE
fix: signal client evaluation

### LINKED ISSUE #483: Bug: user status not disappearing when signal has ended
### Current behaviour 

My status from ytd didnt go away still and when I click status the text changed from my status to let’s hang and when I close the tap, it disappeared

### PR DESCRIPTION
**Pull request by mhenriette**
Closes #483

### CODE REVIEW

**Review by serapieTuyishime — APPROVED** [review]

File: contexts/StatusContext.tsx [hunk 1]
```diff
@@ -29,11 +31,19 @@ export const StatusProvider: React.FC<{ children: React.ReactNode }> = ({
...
+    [signalData?.endsAt],
+  )
+
+  const isOn = useSharedValue(!dateEnded)
   const [temporaryStatus, setTemporaryStatus] = useState<TemporaryStatusType>({
     friendIds: signalData?.friendIds || [],
     activity: signalData?.status_message || "",
     timeSlot: signalData?.when || "NOW",
+    endsAt: signalData?.endsAt || new Date(),
+    startsAt: signalData?.startsAt || new Date(),
```
Comment (chrisostome01) [inline contexts/StatusContext.tsx:46]: Why the default to the the current date?

File: screens/EditSignal/index.tsx [hunk 2]
```diff
@@ -42,21 +42,26 @@ export default function EditSignal({
...
       await queryclient.cancelQueries({ queryKey: ["fetch-my-signal"] })
+      const allFriends = queryclient.getQueryData<Friend[]>(["friends"])
+      const selectedFriends = allFriends?.filter((friend) =>
+        temporaryStatus.friendIds.includes(friend.id),
+      )
       const optimisticStatus: Signal = {
         when: temporaryStatus.timeSlot,
         status_message: temporaryStatus.activity,
-        friends: [],
+        friends: selectedFriends || [],
```
Comment (chrisostome01) [inline screens/EditSignal/index.tsx:52]: Probably, `[]` is not needed?

**Review by chrisostome01 — APPROVED** [review]
